--11: For every situation where student A likes student B, but we have no information about 
--whom B likes (that is, B's id does not appear in the liker_id column of the like table), 
--return A and B's names and grades. Write the SQL in the file sql/11-liked-but-does-not-like.sql
