--12: For each student A who likes a student B where the two are not friends, find if they have a friend C in common 
--(who can introduce them!). For all such trios, return the name and grade of A, B, and C. 
--Write the SQL in the file sql/12-find-friends-in-common.sql